# Name of this GitHub Actions workflow.
name: Semgrep

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]

jobs:
  semgrep_scan:
    name: Semgrep CI
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      # Checkout repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Perform Semgrep Analysis.
      - name: Perform Semgrep Analysis
        run: semgrep scan --config auto ./code_demo

      # Save SARIF results as an artifact.
      - name: Save Scan Results
        run: semgrep scan --sarif --config auto ./code_demo > semgrep-results.sarif

      # Upload SARIF results.
      - name: Upload SARIF results
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: semgrep-results.sarif
